import os

CREDENTIALS_PATH = os.environ.get("CREDENTIALS_PATH")
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")

CRITERIA_REPORTS_DOCUMENT = "1hX_6SQTRp3iprm400GzAq6ImX_8EwtygYfKudnqI2OA"
ACTIVITIES_REPORTS_DOCUMENT = "1SkCYQkrRdsApiaVDCeHJ-nf5ro9rRaFGmKuCciOyzNA"
GENERATIONS_REPORTS_DOCUMENT = "119WqXPSYDkALioEvvWZ_gqoaNIqQlk2X093m9sxPJtM"
INDICES_DOCUMENT = "1iS2zGIcv_e9EkhWB5jH5CVWHzb81h862XgHC-ZF_fCs"

PROMPTS_DOCUMENT = "1Mo0D4-oVvk0ukRDfnYyR09luzyrZ5iNGQmuX1sAzq3A"

ALLOWED_FILETYPES = (".js", ".java", ".py", ".class", ".gitignore")
